name: Codecov

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 14.2
      
      - name: Build and Test
        run:  xcodebuild test -project Rickipedia.xcodeproj -scheme Rickipedia -destination 'platform=iOS Simulator,name=iPhone 14' build test
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
