name: Codecov

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Test
        uses: actions/checkout@v1

      - name: Build and test
        run: |
          xcodebuild clean test Rickipedia.xcodeproj -scheme Rickipedia -destination "platform=iOS Simulator,OS=latest" | xcpretty
          xcodebuild clean test Rickipedia.xcodeproj -scheme RKPDesign -destination "platform=iOS Simulator,OS=latest" | xcpretty
          xcodebuild clean test Rickipedia.xcodeproj -scheme RKPService -destination "platform=iOS Simulator,OS=latest" | xcpretty

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
